version: 2
jobs:
  run_mirror:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pygithub
            python -u mirror_github_org.py
workflows:
  version: 2
  build:
    jobs:
      - run_mirror
  automatic_update:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_mirror
